Don't try to build util/moai if we don't know what OS we're on ...

diff --git a/util/moaiutil b/util/moaiutil
--- a/util/moaiutil
+++ b/util/moaiutil
@@ -16,24 +16,26 @@ then
       bin_build_script="bin/build-linux.sh"
       ;;
     *)
-      bin_build_script="bin/build-linux.sh"
+      bin_build_script=""
       ;;
     esac
 
     if [ -e $bin_build_script ] 
     then
-        echo "Will use the $bin_build_script to build a moai binary for use by moaiutil..."
+        echo "Will use the $bin_build_script to build the util/moai binary for use by moaiutil..."
         $bin_build_script
+    else
+        echo "Could not determine which script to use to build util/moai binary .. aborting"
+        exit 1
     fi
 
     echo "Need to confirm local moai binary was built ..."
     if [ -f $MOAI_SDK_BIN ]
     then
-        MOAI_SDK_BIN=$MOAI_SDK_HOME/util/moai
         echo "Continuing moaiutil execution..."
     else
         echo "Something went wrong with building util/moai .. exiting!"
-    exit 1
+        exit 1
     fi
 fi
 
